"""Checks for modelatlas/depgraph_html.py: the report renders for the small Riverbend fixture and a generated large graph,
holds the outcome, every node id and the class legend, and the embedded JSON parses back to the input; and a graph
whose labels and values are hostile (tags, quotes, '</script>', a placeholder name) renders them as text only, a class
the legend doesn't name still gets a table, and a group with no layer still draws; the first view of a small graph
is never zoomed below 0.8 (a larger one below 0.6), and the Fit button still fits.

    uv run python tests/check_depgraph_html.py
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from modelatlas import depgraph_html  # noqa: E402


def large() -> dict:
    classes = [{"key": k, "name": k.title()} for k in ("outcome", "cashflow", "calculation", "assumption")]
    nodes = [{"id": f"S{i % 8}!r{i}", "kind": "row", "sheet": f"S{i % 8}", "row": i, "label": f"Row {i} </script><b>", "class": classes[i % 4]["key"],
              "layer": i % 12, "value": i * 1.5, "input": i % 9 == 0} for i in range(300)]
    nodes.append({"id": "group:S1", "kind": "group", "sheet": "S1", "label": "40 more rows on S1", "count": 40, "class": "calculation", "layer": 11})
    edges = [{"src": nodes[i]["id"], "dst": nodes[i + 1]["id"], "kind": "direct", "sign": 1} for i in range(299)]
    return {"workbook": "big.xlsx", "start": {"id": nodes[0]["id"], "label": "Out", "value": 1.0}, "classes": classes, "nodes": nodes,
            "edges": edges, "cores": [], "stats": {}, "by_sheet": [{"sheet": "S1", "upstream": 10, "shown": 5}]}


def check(graph: dict, name: str) -> None:
    out = depgraph_html.render(graph)
    m = re.search(r'<script type="application/json" id="graph">(.*?)</script>', out, re.S)
    assert m, name + ": no embedded graph"
    assert json.loads(m.group(1)) == graph, name + ": embedded JSON does not round-trip"
    st = graph["start"]
    assert st["label"] in out and str(st["id"]) in out, name + ": outcome missing"
    for n in graph["nodes"]:
        assert n["id"].replace("&", "&amp;") in out, f"{name}: node {n['id']} missing"
    for c in graph["classes"]:
        assert f'k-{c["key"]}' in out, name + ": no colour for class " + c["key"]
        assert c["name"] in out, f"{name}: class {c['name']} missing"
    assert "nodes.length < 40 ? 0.8 : 0.6" in out, name + ": the first view has no zoom floor for a small graph"
    assert "assumptions &rarr; value" in out and "Generated by Model Atlas " in out and "must be checked by a qualified person" in out
    print(f"ok  {name}: {len(out) // 1024} kB, {len(graph['nodes'])} nodes")


def hostile() -> None:
    bad = '<img src=x onerror="alert(1)">'
    nodes = [{"id": "S!C1", "kind": "cell", "sheet": "S", "row": 1, "cell": "S!C1", "label": "Out __GRAPH__ " + bad,
              "class": "outcome", "layer": 0, "value": bad, "why": "</script>" + bad, "formula": "=A1&\"<b>\""},
             {"id": "S!r2", "kind": "row", "sheet": "S", "row": 2, "label": "x'\"&", "class": "mystery", "layer": 1,
              "value": "<b>v</b>", "pattern": bad, "input": True},
             {"id": "group:S", "kind": "group", "sheet": "S", "label": "3 more rows on S", "count": 3, "class": "calculation"}]
    g = {"workbook": bad, "start": {"id": "S!C1", "label": "Out " + bad, "value": bad},
         "anchors": [{"cell": "S!C1", "label": bad}, {"cell": "X!" + bad, "label": bad}],
         "classes": [{"key": "outcome", "name": "Value outcome"}, {"key": "calculation", "name": "Calculation"}],
         "nodes": nodes, "edges": [{"src": "S!C1", "dst": "S!r2", "kind": "direct"}, {"src": "S!r2", "dst": "group:S", "kind": "collapsed"}],
         "cores": [{"cell": bad, "what": bad, "cashflow": bad, "cashflow_label": bad, "periods": bad, "pv": bad,
                    "method": {"rate": bad, "rate_value": bad}}],
         "stats": {"rows_shown": bad}, "by_sheet": [{"sheet": bad, "upstream": 5, "shown": 1}]}
    out = depgraph_html.render(g)
    blob = re.search(r'<script type="application/json" id="graph">(.*?)</script>', out, re.S)
    assert blob and json.loads(blob.group(1))["nodes"][0]["label"].startswith("Out __GRAPH__"), "embedded JSON broken"
    rest = out[:blob.start()] + out[blob.end():]
    for raw in ("<img", "<b>", "</script><"):
        assert raw not in rest, f"hostile text {raw!r} reached the page unescaped"
    assert rest.count('"nodes":') == 0, "a placeholder inside a label was filled in"
    assert 'k-mystery' in rest and ">mystery<" in rest.replace(" <span", "<"), "a class missing from the legend has no table"
    print("ok  hostile labels and values render as text")


if __name__ == "__main__":
    with open(os.path.join(HERE, "fixtures", "depgraph_fixture.json"), encoding="utf-8") as f:
        check(json.load(f), "riverbend fixture")
    check(large(), "generated large")
    hostile()
